src/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
    :mailer => 'users/mailer',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
    :shared => 'users/shared',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }
  resources :users do
    resources :projects
    resources :appartienes
  end

  resources :projects do
    resources :chats
  end
  
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_sessions
  end
  
  
  root 'root#index'
  post '/votes/:user,:voto', to: 'users#vote', as: 'vote'
  post '/users/:user', to: 'users#promote', as: 'promote'
  patch '/commenta/:project_id,:commento', to: 'projects#commenta', as: 'commenta'
  patch '/projects/:project_id/chats/:chat/edit', to: 'chats#edit', as: 'send'
end

src/app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  require 'open-uri'
  friendly_id :completename, use: :slugged
  ROLES = %i[admin moderator user banned]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :appartienes
  has_many :projects, dependent: :destroy, :through => :appartienes
  has_one_attached :avatar
  validates_length_of :skills, maximum: 400
  validates :name, presence: true,length: {minimum: 2, maximum: 256}
  validates :surname, presence: true,length: {minimum: 2, maximum: 256}
  validates :luogonascita, presence: true,length: {minimum: 2, maximum: 256}
  validates :skills, presence: true,length: {minimum: 2, maximum: 256}
 
  def initialize(role_id = 0)
    @role = ROLES.include?(role_id) ? ROLES[role_id] : ROLES[0]   
    super
  end

  def completename
    "#{name}#{surname}"
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name.split(" ").first  
      user.surname = auth.info.name.split(" ").last 
      image = open(auth.info.image)
      user.avatar.attach(io: image,filename: "#{user.name}#{user.surname}.jpg")
      user.sesso = auth.info.gender
      user.skills = "Enter your skills"
      user.luogonascita = "Enter your hometown"
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

src/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

src/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_path
    end
  end

  def failure
    redirect_to root_path
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

src/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

src/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :configure_account_update_params, only: [:update]
  before_action :configure_sign_up_params, only: [:create]

  def new 
    super
  end

  def create
    super
  end

  def edit
    super
  end
  
  # def update  
  #   super
  # end
  
  def destroy
    @projects = Project.where("user_id= ?" ,@user.id)
    @projects.destroy_all
    @user.destroy
    redirect_to root_path
  end

  protected
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:surname,:email,:password,:datanascita,:luogonascita,:sesso,:skills,:role,:avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:surname,:email,:password,:datanascita,:luogonascita,:sesso,:skills,:role,:avatar])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
 
  protected

  def update_resource(resource, params)
    # Require current password if user is trying to change password.
    return super if params["password"]&.present? || params["email"] != resource.email
    # Allows user to update registration information without password.
    resource.update_without_password(params.except("current_password"))
  end

  private
  def user_params  #non so bene il perchè
      params.require(:user).permit(:name,:surname,:email,:password,:datanascita,:luogonascita,:sesso,:skills,:role,:avatar)
  end

end

src/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  
  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

src/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

src/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    helper_method :vote
    helper_method :promote

    def promote()
        authorize! :destroy, Users
        @user = User.friendly.find(params[:user])
        @user.update(:role => 'admin')
    end

    
    def vote() 
        @user = User.friendly.find(params[:user]);
        @project = Project.friendly.find(params[:id])
        if(Appartiene.where("project_id = ? and user_id = ?",@project.id,current_user.id).first() != nil)   
            @var =(@user.voto).to_i+(params[:voto]).to_i;
            @user.update( :voto => @var)
            if @project == nil
                redirect_to users_path
            else
                redirect_to project_path(@project)
            end
        else
            redirect_to project_path(@project), alert: "Not Authorized"
        end
    end
    
    before_action :authenticate_user!

    def index 
        @users=User.all
        authorize! :index, @users
    end

    def show
        @user = User.friendly.find(params[:id])    
    end
    
    def destroy
        authorize! :destroy, Users
        @user = User.friendly.find(params[:id])
        @user.destroy
        redirect_to users_path, notice: 'User deleted.'
    end


    private 
    def user_params
        params.require(:user).permit(:name,:surname,:email,:password,:datanascita,:luogonascita,:sesso,:skills,:role,:avatar)
    end 

end

src/app/helpers/users_helper.rb
module UsersHelper

end

src/app/views/users/index.html.erb
<div class="ui container">
  <h1>Listing users</h1>
  
  <table class="ui celled table"> 
    <thead>
    <tr><th></th>
    <th>Name</th>
    <th>Surname</th>
    <th>Rate</th>
    <th></th>
    </tr></thead>
    
    <tbody>
    <% @users.each do |user| %>
      <tr>
        
        <% if user.avatar.attached? %>
         <td data-label="image"><img src="<%=(url_for(user.avatar))%>" class="ui circular tiny centered image"></td>
        <% else %>
          <td></td>
        <% end %>

        <td data-label="Name"><%= user.name %></td>
        <td data-label="Surname"><%= user.surname %></td>
        <td data-label="Rate"><%= user.voto %></td>
        <td>
        <%= link_to 'Profile', user_path(user), class: "ui button" %> 
        <% if current_user == user %> 
          <%= link_to 'Edit ', edit_registration_path(user), class: "ui button"%>
        <% end %>
        <% if can? :destroy, Users %>
          <% if user.role != "admin" %>
            <%= link_to "Promote admin", promote_path(:user => user), method: :post ,data: { confirm: "Are you sure?"}, class: "ui button" %>
            <%= link_to "Remove account", user_path(user), data: { confirm: "Are you sure?" }, method: :delete,name: "Cancel my account", id: "Cancel my account", class: "ui button" %>
          <%end%>
        <% end %>
      </tr>   
    <% end %>
    </tbody>
  </table>
</div>

src/app/views/users/show.html.erb
<style>
.column{
  background-color:transparent;
}

.circular.ui.image{
  position:absolute;
  left:0;
  right:0;
}

.ui.items{
  margin-top:30px;
  background-color: #e7e6ed;
  border-radius:30px;
  padding-left:15px;
  max-width:800px;
}
</style>
<div class="ui container">
  <div class="ui items"><br/>
    <div class="item">
      <div class="circular ui small image">
        <% if @user.avatar.attached? %>
          <img src="<%=(url_for(@user.avatar))%>">
        <% else%>
          <img src="/assets/logo.jpg">
        <% end%>  
      </div>
      <div class="content">
        <a class="header"><%=@user.name %> <%= @user.surname %>'s profile</a>
        <div class="meta">
          <span>Skills</span>
        </div>
        <div class="description">
          <p><%=@user.skills%></p>
        </div>
        <div class="extra">
          <i class="map marker alternate icon"></i><%=@user.luogonascita%>
        </div>
      </div>
    </div>
    <br/>
  </div>   
    
  <% if !@user.projects.empty?%>
    <% if current_page?(user_path(current_user)) %>
    <h2>My Projects</h2>
    <% else %>
    <h2><%= @user.name + " " +@user.surname + "'s Projects"%></h2>
    <% end %>
    <div class="ui grid"> 
      <% @user.projects.each do |project| %>
        <div class="four wide column" style="min-width: 250px">
          <div class="ui card">
            <div class="ui small centered image">
              <% if project.avatar.attached? %>
                <img src="<%=url_for(project.avatar)%>">
              <% else %>
                <img src="/assets/logo.jpg">
              <% end %>
            </div>
            <div class="content">
              <div class="header"><%= project.name %></div>
            </div>
            <div class="content">
             <% @user = User.find(project.user_id) %> 
              <div class="ui sub header"><b>Created by:  </b><%= @user.name + " " + @user.surname %></div> 
              <h5></h5>
                <%= project.description%>
            </div>
            <div class = "extra content">
              Created in: <%=project.created_at.to_s[0,10] %>
              
            </div>
            <div class="extra content">
              <% if Appartiene.where("project_id = ? and user_id = ?",project.id,current_user.id).first() != nil %>
                <%= link_to 'Chat', project_chat_path(project_id: project), class: "ui tiny button" %>
              <% else %>
                <%= link_to 'Join Project', new_user_appartiene_path(user_id: current_user.id ,project_id:  project.id),name: "Join project" + project.id.to_s ,id: "Join project" + project.id.to_s  ,data: {confirm: 'Do you really want to join?'}, class: "ui tiny button" %>
              <% end %> 
              <%= link_to  "View Project", project_path(project),id: "View Project"+project.id.to_s,name: "View Project"+project.id.to_s ,method: :get,class: "ui tiny button" %>       
            </div>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>
    
    
    <% if current_page?(user_path(current_user)) %>
      <div class="ui horizontal divider"><h2 class="ui centered header">Create a project: </h2></div>
      <%= render 'projects/form'%>
    <% end %>

    
    <div class = "lst"><br/><br/>
      <%= link_to "Back", :back, class: "ui teal button" %>
      <% if current_page?(user_path(current_user)) %>
      <%= link_to 'Edit User', edit_registration_path(current_user), class: "ui button" %>
      <% end %>
    </div>
  </div>