src/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
    :mailer => 'users/mailer',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
    :shared => 'users/shared',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }
  resources :users do
    resources :projects
    resources :appartienes
  end

  resources :projects do
    resources :chats
  end
  
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_sessions
  end
  
  
  root 'root#index'
  post '/votes/:user,:voto', to: 'users#vote', as: 'vote'
  post '/users/:user', to: 'users#promote', as: 'promote'
  patch '/commenta/:project_id,:commento', to: 'projects#commenta', as: 'commenta'
  patch '/projects/:project_id/chats/:chat/edit', to: 'chats#edit', as: 'send'
end

src/app/models/project.rb
class Project < ActiveRecord::Base
    extend FriendlyId
  
    friendly_id :name, use: :slugged
    has_many :appartienes
    has_many :user ,dependent: :destroy,:through => :appartienes
    has_many :chat, dependent: :destroy
    has_one_attached :avatar

    validates :name, length: {minimum: 2} 
    validates :description, length: {minimum: 2} 
    validates :requisitipartecipazione, length: {minimum: 2} 

    def listUser(id)
        @appartienes = Appartiene.where("project_id = ? ",id)
        @size = @appartienes.size
        utenti = Array.new
        while (@size>0)
            @size = @size - 1
            utenti.push(@appartienes[@size].user_id)
        end
        return utenti
    end

    def stampaUtenti(id)
        @users = User.where("id = ?",id)
        return @users[0]
    end

    def parsingComments(project)
        @size = project.commenti.size
        pComments = Array.new
        pComments = project.commenti.split("\n\n")
        pComments.shift(1)
        return pComments 
    end

end

src/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    helper_method :commenta
    
    def commenta
            @c = params[:project]
            @project = Project.friendly.find(params[:project_id])            
            if(@c["message_new"].length == 0)
                redirect_to project_path(@project)
                flash[:alert] = "Comments must be at least 1 character long"
            else
                @name = current_user.name
                @time = Time.now
                @commmenti = @project.commenti + "\n\n" +  @name + " " + @current_user.surname+ ': ' + @c["message_new"] + ";;" + @time.to_s.truncate(19, omission: '') 
                @project.update(:commenti => @commmenti)
                redirect_to project_path(@project)
        end
    end

    before_action :authenticate_user!
    before_action :require_permission, only: [:destroy]

    def index
        @project=Project.all 
    end 

    def show
        @project = Project.friendly.find(params[:id])
    end

    def create
        @p=params[:project]
        @user = User.friendly.find(params[:user_id])
        if(@p["name"].length < 2)
            redirect_to user_path(@user)
            flash[:alert] = "Project's name must be at least 2 character long"
        else
            @project = @user.projects.create(project_params)
            @appartienes = Appartiene.where("project_id = ? and user_id = ?",@project.id,@user.id);
            @project.update(:user_id => @user.id, :appartienes_id => @project.id)
            @chat = @project.chat.create(params[:id])
            @appartienes.update(:admin => true)
            @project.update(:chat_id => @chat.id)

            redirect_to user_path(@user)
        end
    end

    def destroy
        @user = User.friendly.find(params[:user_id])
        @project = @user.projects.friendly.find(params[:project])
        @appartienes = Appartiene.where("project_id = ? and user_id = ?",@project.id,@user.id)
        @var = @project.appartienes_id
        @project.destroy
        redirect_to user_path(@user)
    end

    def edit
        @project = Project.friendly.find(params[:id])        
        if(Appartiene.where("project_id = ? and user_id = ? and admin = ?",@project.id,current_user.id,1).first() == nil)
            redirect_to project_path(@project), alert: "Not Authorized"
        end
    end

    def update #da sistemare
        @project = Project.friendly.find(params[:id])        
        if(Appartiene.where("project_id = ? and user_id = ? and admin = ?",@project.id,current_user.id,1).first() != nil)
            @new = params[:project]
            @project.update(id: @project.id, description: @new["description"], linkesterno: @new["linkesterno"], requisitipartecipazione: @new["requisitipartecipazione"], avatar: @new["avatar"])
            redirect_to project_path(@project), success: "Project modified"  
        else
            redirect_to project_path(@project), alert: "Not Authorized"
        end
    end

    protected
    def require_permission
        @user = User.friendly.find(params[:user_id])   
        if current_user != @user
            redirect_to ('/404')
        end
        @appartienes = Appartiene.where("project_id = ? and user_id = ?",params[:project],params[:user_id])
        if(@appartienes.any?)
            if(!@appartienes[0].admin)
                redirect_to ('/404')
            end 
        end
    end


    private
    def project_params
        params.require(:project).permit(:name,:description,:linkesterno,:requisitipartecipazione,:commenti,:chat,:message_new,:avatar)
    end
    def comment_params
        params.require(:project).permit(:commenti,:message_new,:commento)
    end
        
    def commenta_params
        params.require(:project).permit(:message, :message_new,:project_id)
    end

end

src/app/helpers/projects_helper.rb
module ProjectsHelper
end

src/app/views/projects/_form.html.erb
<div class="ui centered grid">
  <br/><%= form_with(model: [ current_user, current_user.projects.build ], local: true, :html => {:class => "ui form"}) do |form| %>
    
    <%= form.label :project_logo%><br/>
    <div class="ui input">
      <%= form.file_field :avatar, accept: 'image/png,image/jpeg'%>
    </div><br/>

    <%= form.label :name %><br/>
      <div class="ui input">
      <%= form.text_field :name, autocomplete: "off" %>
    </div><br/>

    <%= form.label :description %><br/>
    <div class="ui input">
      <%= form.text_area :description, style: "height: 5%; width: 400px" %>
    </div><br/>
    
    <%= form.label :project_requirement %><br/>
    <div class="ui input">
      <%= form.text_area :requisitipartecipazione, style: "height: 5%; width: 400px" %>
    </div><br/> 
    
    <%= form.label :external_link %>   <br/> 
    <div class="ui labeled input">
      <div class="ui label">
      https://
      </div>
      <%= form.text_field :linkesterno, style: "width: 330px" %>
    </div><br/>
     
    <div><br/>
      <%= form.submit "Create Project", class: "ui button" %>
    </div>
  <% end %>
</div>

src/app/views/projects/_project.html.erb
<div class = "cont">
  <p>
    <strong>Project:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>
  <p>
    <strong>Link al progetto:</strong>
    <a href = "<%= "https://www."+project.linkesterno%>" target = "new"> <%= project.linkesterno%></a>
  </p>
    <%= link_to 'View Project', project_path(project), class: "btn btn-primary" %>
  </p>
</div>

src/app/views/projects/edit.html.erb
<div class="ui container">
  <h1>Edit Project</h1>
  <div class = "ui grid">
  <%@prg = Project.friendly.find(params[:project])%>
  <%@uid = params[:user_id]%>
    <%= form_for(@prg, url: project_path(id: @prg.id), :html => {:class => "ui form", style: "min-width: 70%"}) do |form| %>
      <div>
        <%= form.label :description %><br>
        <%= form.text_area :description %>
      </div><br/>
      <div>
        <%= form.label :external_link %><br>
        <div class="ui labeled input">
          <span class="ui label" >
          <div>https://</div>
          </span>
          <%= form.text_field :linkesterno %>
        </div>
      </div><br/>
      <div>
        <%= form.label :project_requirement %><br>
        <%= form.text_area :requisitipartecipazione %>
      </div><br/>
      <div>
        <%= form.label :avatar %>
        <%= form.file_field :avatar, accept: 'image/png,image/jpeg' %>
      </div><br/>
      <div>
        <div class="mt"><%= link_to 'Back', project_path(@prg), class: "ui teal button" %><%= form.submit "Edit Project", class: "ui blue button" %></div>
      </div>
    <% end %>
  </div>
</div>

src/app/views/projects/index.html.erb
<style>
.column{
  background-color:transparent;
}
</style>
<div class="ui container">

  <div class="ui header"><h1>Listing Projects</h1><br/></div>

  <div class="ui grid"> 
    <% if Project.all.size != 0%>   
      <% Project.all.each do |project| %>
        <div class="four wide column" style="min-width: 250px">
          <div class="ui card">
            <div class="ui small centered image">
              <% if project.avatar.attached? %>
                <img src="<%=url_for(project.avatar)%>">
              <% else %>
                <img src="/assets/logo.jpg">
              <% end %>
            </div>
            <div class="content">
              <div class="header">  <%= project.name %></div>
            </div>
            <div class="content">
              <% @user = User.find(project.user_id) %>             
              <div class="ui sub header"><b>Created by:  </b><%= @user.name + " " + @user.surname %></div>
              <h5></h5>
                <%= project.description%>
            </div>
            <div class = "extra content">
              Created in: <%=project.created_at.to_s[0,10] %>
              
            </div>
            <div class="extra content">
              <% if Appartiene.where("project_id = ? and user_id = ?",project.id,current_user.id).first() != nil %>
                <%= link_to 'Chat', project_chat_path(project_id: project, id: project.id), class: "ui tiny button" %>
              <% else %>
                <%= link_to 'Join Project', new_user_appartiene_path(user_id: current_user.id ,project_id:  project.id),name: "Join project" + project.id.to_s ,id: "Join project" + project.id.to_s  ,data: {confirm: 'Do you really want to join?'}, class: "ui tiny button" %>
              <% end %> 
              <%= link_to  "View Project", project_path(project),id: "View Project"+project.id.to_s,name: "View Project"+project.id.to_s ,method: :get,class: "ui tiny button" %>       
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class=content><br/>No project available<br/></div>
    <% end %>
  </div>
</div>

src/app/views/projects/show.html.erb
<style>
.comments{
  max-width:100px
}
</style>
<div class="ui container">
  <% project=Project.friendly.find(params[:id]) %>
  <div class="container">
    <div class="ui items">
      <div class="item">
        <div class="image">
          <% if project.avatar.attached? %>
            <img src="<%=url_for(project.avatar)%>" width="100" heigth="100">
            <% else %>
            <img src="/assets/logo.jpg" width="100" heigth="100">
          <% end %>
        </div>
        <div class="content">
          <a class="header"><%=project.name%></a>
          <div class="meta">
            <span>Description</span>
          </div>
          <div class="description">
            <p><%=project.description%></p>
          </div>
          <div class="meta">
            <span>External link:</span>
          </div>
          <div class="description">
            <% if project.linkesterno.to_s != "Non presente"%>
              <a href = "<%="https://www."+project.linkesterno%>" target = "new"><%= project.linkesterno%></a>
            <%end%>
          </div>
        </div>
      </div>
    </div>

      <%if current_user.id != project.user_id && Appartiene.where("project_id = ? and user_id = ?",project.id,current_user.id).first() != nil%>
          <td><%= link_to 'Leave Project', user_appartiene_path(user_id: current_user.id, project_id: project.id), method: :delete, data: {confirm: 'are you sure about that?!'}, class: "ui button" %></td>
      <%end%>

      <% if Appartiene.where("project_id = ? and user_id = ?",project.id,current_user.id).first() != nil %>
          <%= link_to 'Chat', project_chat_path(project), class: "ui button" %>

      <% else %>
          <%= link_to 'Join Project', new_user_appartiene_path(user_id: current_user.id ,project_id:  project.id), data: {confirm: 'are you sure about that?!'}, class: "ui button" %>
      <% end %>
      
      <% if current_user.id == project.user_id %>
        <td><%= link_to 'Edit Project', edit_project_path(project: project), class: "ui button" %></td>
        <td><%= link_to 'Destroy Project', project_path(user_id: project.user_id, project: project,id: project.id), method: :delete,id: 'Destroy Project', name: 'Destroy Project' ,data: {confirm: 'are you sure about that?!'}, class: "ui secondary button" %></td>
      <%end%>  
      <br/>
      <br/>

      <strong>Membri del progetto:</strong>
      <%  
      @nomi = project.listUser(project.id);
      @size =  @nomi.size;
      @listUsers = Array.new
      while (@size>0)
        @size = @size - 1;
        @listUsers.push(project.stampaUtenti(@nomi[@size]));
      end
      %>
      <table>
      <td> <% @listUsers.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.surname %></td>
          <td><%= user.voto %></td>
          <% if current_user == project.user_id%>
            <td><%= link_to 'Project Manage', user_path(user), class: "ui button" %></td>      
            <td><%= link_to 'Edit ', edit_registration_path(user), class: "ui button"%></td>
          <% else%>
            <% if current_user != user%>
              <td><%= link_to 'Like', vote_path(:user=>user,:voto=>1, :id=>project.id), method: :post, class: "ui button"  %>
              <%= link_to 'Dislike', vote_path(:user=>user,:voto=>-1, :id=>project.id), method: :post, class: "ui button"  %></td>
            <% end %>
            <td><%= link_to 'View Profile', user_path(user), class: "ui button" %></td>
          <% end %>
          </tr>
        </tr>   
      <% end %></td>
      </table>

        <div class="ui comments">
          <h3 class="ui dividing header">Comments</h3>
            <%comments = project.parsingComments(project)
              comments.each do |comment|
              if(comment.length>1) 
                column = comment.index(':')
                message = comment[column+1..].split(";;")%>
                <div class="ui comment">
                  <div class="content">
                    <b><%=comment[0,column]%></b>
                    <div class="metadata">
                      <span class="date"><%=message.second[0..-4]%></span>
                    </div>
                    <div class="text">
                        <%=  message.first%>
                    </div>
                  </div>
                
              <%end%>
              </div>
            <%end%>
            <%= form_for(project, url: commenta_path(project.id, :message_new), :html => {:class=>"ui reply form"}) do |s| %>
            <%= s.text_field  :message_new, autocomplete: "off" %>
            <br/>
              <div>
              <br/>       
                <div class="ui input">
                  <%= button_tag type: 'submit', class: "ui blue labeled submit icon button" do %>
                      <i class="icon edit" ></i>Post comment
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
    <br/>
    <div class="lst"><%= link_to "Back", projects_path(), class: "ui teal button" %></div>
    
  </div>
</div>