src/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
    :mailer => 'users/mailer',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
    :shared => 'users/shared',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }
  resources :users do
    resources :projects
    resources :appartienes
  end

  resources :projects do
    resources :chats
  end
  
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_sessions
  end
  
  
  root 'root#index'
  post '/votes/:user,:voto', to: 'users#vote', as: 'vote'
  post '/users/:user', to: 'users#promote', as: 'promote'
  patch '/commenta/:project_id,:commento', to: 'projects#commenta', as: 'commenta'
  patch '/projects/:project_id/chats/:chat/edit', to: 'chats#edit', as: 'send'
end

src/app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :project
  def parsingChat(chat)
    @size = chat.message.size
    pMsgs = Array.new
    pMsgs = chat.message.split("\n\n")
    pMsgs.shift(1)
    return pMsgs 
  end
end

src/app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  before_action :authenticate_user!
  before_action :require_permission, only: [:new, :create, :show, :edit]

  def pRefresh
    render :partial => "chats/display"
  end

  def new           #da chiamare solo alla creazione del progetto
    @chat = Chat.new
  end

  def create        #da chiamare solo alla creazione del progetto
    @project = Project.friendly.find(params[:project_id])
    @chat = @project.chat.build(chat_params)
    if @chat.save
      flash[:success] = 'Chat added!'
      @project.chat_id= @chat.id
    else            #NO
      render 'new'
    end
	end
	
  def show
    @project = Project.friendly.find(params[:project_id])
    @chat = Chat.find(@project.chat_id)
	end

  def update
    @c = params[:chat]
    @project = Project.friendly.find(params[:project_id])
    @chat = Chat.find(@project.chat_id)
    if(@c["message_new"].length ==0)
      redirect_to project_chat_path(@chat.project_id, @chat)
    else
      @name = current_user.name
      @time = Time.now
      @old = @chat.message
      @chat.message = @old + "\n\n" + @name + " " + @current_user.surname + ': ' + @c["message_new"] + ' ;; ' + @time.to_s.truncate(19, omission: '')
      @chat.update(:message => @chat.message)
      redirect_to project_chat_path(@chat.project_id, @chat)
    end
  end
  
  protected_methods
  def require_permission
    @project = Project.friendly.find(params[:project_id])
    @appartienes = Appartiene.where(project_id: @project.id,user_id: current_user.id).first()
    if (!@appartienes || @appartienes.user_id != current_user.id)
      redirect_to ('/404')
    end
  end

  private

  def chat_params
    params.require(:project_id).permit(:project_id, :message, :message_new)
  end
  
  def new_send_params
    params.require(:chat).permit(:message, :message_new)
  end

end

src/app/helpers/chat_helper.rb
module ChatHelper
end

src/app/helpers/chats_helper.rb
module ChatsHelper
end

src/app/views/chats/_display.html.erb
<div class="ui comments" id = "messaggi">
  <h2 class="ui dividing header" id="chat">Chat</h2>
  <% msgs = @chat.parsingChat(@chat)
    msgs.each do |msg|
      if(msg.length>1)
        column = msg.index(':')
        message = msg[column+1..].split(";;")%>
        <div class="ui comment">
          <div class="content">
            <b><%=msg[0,column]%></b>
            <div class="metadata">
              <span class="date"><%=message.second[0..-4]%></span>
            </div>
            <div class="text">
                <%=  message.first%>
            </div>
          </div>
        
      <%end%>
      </div>
    <%end%>
  </div>

src/app/views/chats/_send.html.erb
<%= form_for(@chat, url: project_chat_path(@chat.project_id, @chat.id), :html => {:class => "ui reply form flx", style: "width: 80%;"}) do |s| %>
	<%= s.text_field :message_new,autocomplete: "off", minlength: 1, id: "txt" %>
	<button type="submit" class="ui button icon blue" style="margin-left: 5px;">
		<span style="margin-right: 2px;">Send</span><span><i class="icon paper plane"></i></span>
	</button>
<% end %>

src/app/views/chats/show.html.erb
<<body onload = "updateDiv();">
<div class="ui container" >
  <% project=Project.friendly.find(@chat.project_id) %>
  

  <div class="ui items">
    
    <div class="item">
      <div class= "image" style="width: 80px;">
        <img src="/assets/logo.jpg">
      </div>
      <div class="content">
        <p>Project:</p>
        <p class="header"><%=project.name%>
        <%# <p style="margin-top: 3px;">Chat-id: <%=@chat.id></p> %>
      </div>
    </div>
  </div>

      <%= render "chats/display"%>
      
      <%= render "chats/send" %>

  <div class="mt"><%= link_to 'Back', project_path(project), class: "ui teal button" %></div>
</div>
</body>