src/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
    :mailer => 'users/mailer',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
    :shared => 'users/shared',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }
  resources :users do
    resources :projects
    resources :appartienes
  end

  resources :projects do
    resources :chats
  end
  
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_sessions
  end
  
  
  root 'root#index'
  post '/votes/:user,:voto', to: 'users#vote', as: 'vote'
  post '/users/:user', to: 'users#promote', as: 'promote'
  patch '/commenta/:project_id,:commento', to: 'projects#commenta', as: 'commenta'
  patch '/projects/:project_id/chats/:chat/edit', to: 'chats#edit', as: 'send'
end

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title >ProjectAdvisor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

      <nav class="ui inverted menu">
        <%=link_to '', root_path(), class: "logo"%>
        <%= link_to '<i class="file outline icon"></i>'.html_safe + 'Projects', projects_path(), class: "ui secondary button"%>
        <% if !user_signed_in? %>
        <div class="right menu">
          <%=link_to '<i class="sign-in icon"></i>'.html_safe + 'Log in', new_session_path(User), class: "ui secondary button" %>
          <%=link_to '<i class="pen square icon"></i>'.html_safe + 'Sign up', new_registration_path(User), class: "ui secondary button" %>
        </div>
        <% end %>
        

        <% if user_signed_in? %>
        <div class="right menu">
          <% if can? :index, Users %>
            <%= link_to '<i class="lock icon"></i>'.html_safe + "User Index", users_path(), class: "ui secondary button" %>
          <% end %>
          <%=link_to '<i class="user icon"></i>'.html_safe + current_user.name, user_path(current_user), :id=>"Profilo" ,:name=>"Profilo",class: "ui secondary button" %>
          <%=link_to '<i class="sign-out icon"></i>'.html_safe + 'Logout', destroy_user_session_path, :method => :delete, class: "ui secondary button"%>
        </div>
        <% end %>
      </nav>
      
      <% flash.each do |name,msg| %>
        <div class="ui middle aligned center aligned grid"><br/>
          <div class='<%= flash_class(name) %>'>
          <%= msg %>
          </div>
        </div><br/>
      <% end %>

      <%= yield %>


  </body>
</html>